import { StyleSheet, Platform } from "react-native";
const Fonts = {
    PretendardBold: "Pretendard-Bold",
    Pretendard: "Pretendard-Medium",
    PretendardThin: "Pretendard-Thin"
}

const styles = StyleSheet.create({
    block: { flex: 1, backgroundColor: '#fff' },

    

    defaultBtn: { backgroundColor: "blue", padding: 5, },
    defaultBtnText: { color: "#fff" },
    whiteBlock: { backgroundColor: "#fff" },
    ViewInner: { marginRight: 15, marginLeft: 15, },
    ViewInner10: {marginRight: 10, marginLeft: 10, },
    commonPaddingLeft : {paddingLeft:15},
    commonPaddingRight : {paddingRight:15},
    commonMarginLeft : {paddingLeft:15},
    MainViewGrayBar : {borderBottomWidth:5, borderBottomColor:"#F4F4F4"},
    MainViewGrayBar10 : {borderBottomWidth:10, borderBottomColor:"#F4F4F4"},
    ActivityIndicatorBack : {width:"100%",height:"100%",position:"absolute",flex:1,backgroundColor:"rgba(255,255,255,0.5)",zIndex:3,left:0, top:0, justifyContent:"center"},

    commingsoonBack : {flex:1,flexDirection:"column",justifyContent:"center"},
    commingsoonBackText: {color:"#fff", textAlign:"center"},

    /*커스텀 헤드*/
    PDSView: {},
    PDSShareView: { paddingTop: 10, flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 15, height: 55, borderBottomWidth: 1, borderBottomColor: "#E6E6E6", },
    PDSShareViewLeft: { textAlign: "left", alignItems: "flex-start", paddingTop: 10, width: 50},
    PDSShareViewMid: { justifyContent: "flex-start",flex:1},
    PDSShareViewMidText: { fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 18, color: "#0d0d0d", width: "100%", textAlign: "center", lineHeight: 18, paddingTop: 10,  },
    PDSShareViewRight: { flex: 1, textAlign: "right", alignItems: "flex-end", paddingTop: 10, width: 100, },
    PDSShareViewRightCust: { width:50, textAlign: "right", alignItems: "flex-end", justifyContent:"center"},
    PDSShareViewRightCustText:{fontSize:15,color:"#004FFF",fontWeight:"600"},
    PDSShareViewMidNoneData : {flex:1, },
    PDSShareViewMidNoneDataText: {textAlign:"center"},

    PDSShareViewLoginBox :{padding:15,paddingVertical:50,justifyContent:"center",alignItems:"center"},
    PDSShareViewLoginBoxText :{fontSize:14,color: "#0d0d0d", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    PDSShareViewLoginBoxBtn :{backgroundColor:"#cd2214",paddingVertical:7,paddingHorizontal:30,borderRadius:4,marginTop:10,},
    PDSShareViewLoginBoxBtnText :{fontSize:16,color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},

    /*커스텀 인풋*/
    InputSearch:{borderWidth:1, borderColor:"#e6e6e6",marginTop:20,marginBottom:20, flexDirection:"row"},
    TxtInputType:{height:40,justifyContent:"center", paddingHorizontal:5,}, 
    TxtInputTypeText : {},
    searchgayimg:{width:18, height:18, alignItems:"center", justifyContent:"center",},
    InputSearchBotton:{ justifyContent: 'center',alignItems: 'center',margin: 10,},
    CustomeInputTxtArea:{flex:9},
    CustomeInputTxtArea02:{flex:1},
    CustomeInputImgArea:{flex:1, alignItems:"center", justifyContent:"center"},
    InputSearchAutoView : {},
    InputSearchAutoViewToView: {paddingVertical:7},
    InputSearchAutoViewToText: {fontSize:15,fontFamily: Fonts.Pretendard,},


    /*플로팅버튼*/
    FloatingBtnArea: {
        zIndex: 1, position: 'absolute', bottom: 16, right: 16, width: 50, height: 50, borderRadius: 50,
        // iOS 전용그림자 설정
        shadowColor: "#4d4d4d", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 4,
        // 안드로이드 전용그림자설정
        elevation: 5,
        //안드로이드에서 물결 효과가 영역 밖으로 나가지 않도록 설정
        //iOS에서는 overflow가 hidden일 경우 그림자가 보여지지 않음
        overflow: Platform.select({ android: "hidden" }),
    },
    FloatingBtn: { width: 50, height: 50, backgroundColor: "#cd2214", borderRadius: 50, alignItems: "center", justifyContent: "center" },
    TradeWriteBtn: { width: 50, height: 50, backgroundColor: "#cd2214", borderRadius: 50, alignItems: "center", justifyContent: "center" },
    TradeAddBtn: { width: 16, height: 16, },

    /*MainScreen*/
    JLAView : { paddingHorizontal: 20,flex:1},
    MLView: { flex: 1, padding: 26 },
    MlViewInner: { flex:1, justifyContent: "center", alignItems: "center" },
    MLimage: { resizeMode: "contain", width: 60, height: 60 ,marginBottom:60,},
    IPBox: { marginTop: 10, },
    MLInputF: { fontSize: 13, paddingVertical: 8, borderColor: "#dfdfdf", borderWidth: 1, marginBottom: 15, width: "100%", paddingLeft: 10, paddingRight: 10, borderRadius: 5 },
    JoinBox:{alignItems:"center" ,marginBottom:30 },
    LoseBox:{},
    MadeAccount:{flexWrap: "wrap",marginTop:20, alignItems:"center",},
    MdAccText:{backgroundColor:"#f2f2f2",paddingTop:8, paddingBottom:8, paddingRight:30, paddingLeft:30, fontSize:13, borderRadius:20, textAlign:"center"},
    SNSLogin:{marginTop:20},
    loginSNSLogo:{width:60, height:60},
    SNSArea:{flexDirection:"row",  marginTop:30, justifyContent:"center",},
    SNSImg:{marginRight:10},




    /* MainScreenArea: {flex:1, flexDirection:'column',},*/

    MainTopArea: { flexDirection: 'row', borderBottomWidth: 0, borderBottomColor: "#E6E6E6",justifyContent: "space-between"},
    MainTopAreaFiexd : {},
    MainHeaderPadding : {paddingVertical:10, paddingHorizontal:15},
    MainMoveBtn: {},


    MainDropBox: { alignItems: 'center', flex: 1, flexDirection: "row" },
    MainDropBox2: { width: 50, justifyContent: "center" },
    MainBackBtn : {paddingVertical:15,paddingHorizontal:15},
    MainDropTextView: { flex: 1 },
    MainDropText: { color: "#0d0d0d", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 16, },
    MainDropTextLeft: {textAlign:"left", color: "#0d0d0d", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 18, },
    MainDropTextLeftSmall: {textAlign:"left", color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14, },

    MainAlarmAreaLogo : {paddingVertical:10,paddingHorizontal:15, width:50,  justifyContent:"center"},
    MainHeadLogo : {height:30,width:30, },

    MainAlarmArea: { flexDirection: 'row', width:50, justifyContent:"flex-end"},
    MainAlarmContainer: { justifyContent: "center", alignItems: "flex-end", paddingHorizontal: 15 , paddingLeft:5},
    MainAlarmContainerNoPad: {paddingHorizontal: 0 ,paddingLeft:15},
    MainAlarmImg: { resizeMode: "contain", width: 24, height: 24, },
    MainTopLocal: { fontSize: 14, fontWeight: "600", color: "#333" },
    MainTopLocalImg: { width: 10, height: 8 },

    MainMoreBtn : {flexDirection:"row",justifyContent:"space-between",paddingVertical:13,borderRadius:4,borderWidth:1,borderColor:"#00B267"},
    MainMoreBtnText:{flex:1,textAlign:"center",color:"#00B267"},
    MainMoreBtnImage: {paddingRight:15,paddingTop:2,},

    miriRel: {position:"relative"},
    miriAbs: {position:"absolute",bottom:10,opacity:0.9},

    MainMoreBtn2 : {flexDirection:"row",justifyContent:"space-between",paddingVertical:13,borderRadius:4,borderWidth:0,backgroundColor:"#00B267"},
    MainMoreBtnText2:{flex:1,textAlign:"center",color:"#fff"},

    MainLocView : {paddingVertical:10,paddingHorizontal:20},
    MainLocViewText : {fontSize:16,color: "#0d0d0d", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    MainLocPress : {paddingVertical:5,},
    MainLocViewShare : {flexDirection:"row",},
    MainLocPressStart : {flex:1},
    MainLocPressEnd : {width:40,alignItems:"flex-end"},

    MainViewContentArea: { position: "relative" },
    MainVisualArea: { flexDirection: "row", paddingTop: 25, paddingBottom: 25, borderBottomWidth: 1, borderBottomColor: "#E6E6E6" },
    MainVisual: { width:90, position:"relative",},
    MainVisualTxtArea: { flex: 4,  flexDirection: "column", },
    MainVisualImg: { width: 80, height: 80, borderRadius:4},
    LikeArea: { flexDirection: "row", flex: 1, justifyContent: "flex-end", paddingRight: 5 },
    LikeAreaImg: { width: 15, height: 15, marginRight: 5 },
    MainVisualTitle: { fontSize: 14, fontFamily:Fonts.Pretendard, color: "#0d0d0d", lineHeight: 20, letterSpacing: -.5 },
    MainVisualLocalInfo: { fontSize: 13, color: "#808080", lineHeight: 20 },
    MainVisualPrice: { fontSize: 14, fontWeight: "600", color: "#0d0d0d", lineHeight: 19 },

    /*TradeWriteScreen*/
    TradeWriteInsertImage: { flexDirection: "row", marginTop: 30, marginBottom: 20, },
    InsertArea: { flex: 1, },
    SelectImageArea: { flex: 2, justifyContent: "center", alignItems: "center", },
    AddImageBtn: { width: 80, height: 80, borderRadius: 80, backgroundColor: "#F9F9F9", borderColor: "#ccc", borderWidth: 1 },
    AddPictureImage: { width: 33, height: 27 },
    AddPictureTXT: { textAlign: "center", fontSize: 12, lineHeight: 20 },
    AddImageCircle: { alignItems: "center", justifyContent: "center", width: 80, height: 80, flexDirection: "column", flex: 1 },
    SelectImageShow: { flexDirection: "row", flex: 1, flexWrap: "wrap" },
    SelectImges: { width: 32, height: 32, marginRight: 5, marginBottom: 5, },
    TradeWriteArea: {},
    TWBottomAbsolunt: { color: "#fff" },
    TradeWriteInfo: { color: "#000", fontSize: 14, fontWeight: "600", marginBottom: 10, marginTop: 10 },
    TradeWriteInputForm: { borderWidth: 1, borderColor: "#e6e6e6", marginBottom: 15, },
    TradeWriteInputForm02: { borderWidth: 1, borderColor: "#e6e6e6", marginBottom: 15, flexDirection:"row",alignItems:"center"},
    TradeWriteInputType: { lineHeight: 15, height:40 ,paddingHorizontal:15,paddingVertical:0},
    TradeWriteInputType02: { lineHeight: 15, flex:3,},
    LocalSearchBtn:{flex:1,},

    TradeWriteBottomArea: { position: "absolute", bottom: 0, backgroundColor: "#cd2214", flexDirection: "row" },
    TradeWriteBottomBtn: { color: "#fff", height: 50, flex: 1, justifyContent: "center", alignItems: "center", },
    TWPlaceSearchBox: { borderWidth: 1, paddingtop: 10, marginBottom: 100, borderColor: "#e6e6e6" },
    TWPlaceSearchTxtBox: { flex: 1, flexDirection: "row", paddingTop: 10, paddingBottom: 10 },
    TWPlaceSearchTxtLt: { alignItems: "flex-start", flex: 2, paddingLeft: 20, },
    TWPlaceSearchTxtRt: { alignItems: "flex-end", flex: 1, paddingRight: 20, },
    TWPlaceSearchTxt01:{color:"#ccc"},
    MoveArrow:{color:"#333"},



    /* TradeMapScreen */
    MapArea: { backgroundColor: "#dfdfdf", flex: 1, alignItems: "center", justifyContent: "center", },
    MapGuideTest: { color: "#fff", fontSize: 30 },

    /* SearchIndexScreen */

    SearchScreenInputArea: { marginTop: 10 },
    RecentSearchBox: { marginBottom: 20, flexDirection: "row", flexWrap: "wrap", },
    RecentSearchTxt: { flexDirection: "row", alignSelf: "flex-start", paddingLeft: 10, borderRadius: 30, marginRight: 10, marginBottom: 10, borderColor:"#404040",borderWidth:1},
    RecentSearchTxtStyle: { paddingRight: 5, fontSize: 13, lineHeight: 27, color:"#404040"},
    RecentSearchTxtImageBox: { justifyContent: "center" ,paddingHorizontal:10,paddingLeft:8},
    RecentSearchTxtImageStyle: { width: 10, height: 10, justifyContent: "center", },
    AssociaatedSearch: {},
    AssociaatedSearchTxt: { fontSize: 14, color: "#868686", lineHeight: 28, alignSelf: "flex-start", marginTop: 10, paddingRight: 10 },
    SearchNoData : {alignItems:"center", flex:1,paddingVertical:100,},
    SearchNoDataText : {textAlign:"center",paddingTop:20},

    /* AlarmListScreen */
    AlarmAreaInterval: { marginTop: 10, marginBottom: 10 },
    AlarmContentArea: {paddingVertical:10, flexDirection: "row", marginBottom: 10, flexWrap: "wrap", paddingHorizontal:10,},
    AlarmContentAreaActive: {backgroundColor:"#F4F4F5", borderRadius:4},
    AlarmcontentImage: { flex: 1 },
    AlarmcontentDetail: { flex: 5, flexDirection: "column" },
    AlarmUserAreaTypeView: {},
    AlarmUserAreaTypeText: {fontSize: 12, color: "#000",fontFamily: Fonts.PretendardBold, letterSpacing: -.5, },
    AlarmcontentImageBox: { borderwidth: 1, borderColor: "#000" },
    AlarmUserImge: { width: 40, height: 40, borderRadius: 40, },
    AlarmUserArea: { flex: 1, alignSelf: "flex-start" },
    AlarmUserNameArea: { flexDirection: "row", alignSelf: "flex-start", flexWrap: "wrap", marginBottom: 5 },
    AlarmUserName: { color: "#cd2214", alignSelf: "flex-start" },
    AlarmDetailBasic: { color: "#000", fontSize:13,},
    AlarmDetailLike: { color: "#000", },
    AlarmDetailComment: { color: "#000", },
    AlarmDetailTimeArea: { flex: 1 },
    AlarmDetailTime: { color: "#9DA0A2", fontSize: 12 },


    /* CategoryClass */
    CategoryAreaTitle : {fontSize: 17, color: "#333", fontFamily: Fonts.Pretendard,letterSpacing:-.5},
    CategoryAreaTitleView: {marginBottom:10,},
    CategoryArea:{flexDirection:"row",flexWrap:"wrap",textAlign:"center", marginTop:10},
    CategoryInterver:{width:"50%",},
    CategoryBox:{marginBottom:15,flexDirection:"row"},
    CategoryTypeBox:{  width:20, heihgt:20},
    CategoryTypeText:{textAlign:"center", color:"#000",fontWeight:"500",lineHeight:21,marginLeft:5},
    CategoryBoxInterval:{marginRight:"5%"},


    /* MainViewScreen */
    MainViewSliderImg:{width:"100%", height:400,},
    MainViewCostomHd:{position:"absolute", zIndex:1, right:0, width:"100%"},
    MainViewCostomHd2:{position:"absolute", zIndex:1, left:0, width:"100%"},
    MainViewProfile:{paddingTop:0, paddingbottom:20,},

    MainHeadLogoView : {justifyContent:"center",flex:1, alignItems:"center",paddingVertical:5,paddingLeft:15},

    mainScreenSearchView:{paddingHorizontal:15,paddingVertical:5,position:"relative"},
    mainScreenSearchPress: { alignItems:"center", flexDirection:"row", borderWidth:1,borderColor:"#999",height:40,justifyContent:"flex-start",paddingHorizontal:15,borderRadius:4,width:"100%"},
    MainSearchImg : {height:25,width:25,},

    subScreenSearchView:{flexDirection:"row"},
    subScreenSearchViewLeft: {width:30,paddingVertical:15,paddingHorizontal:15,},
    subScreenSearchViewRight: {flex:1,paddingHorizontal:15,paddingVertical:5,position:"relative",},
    subScreenSearchPress: { alignItems:"center", flexDirection:"row", borderWidth:1,borderColor:"#999",height:40,justifyContent:"flex-start",paddingHorizontal:15,borderRadius:4,width:"100%",paddingLeft:10},
    subSearchImg : {height:25,width:25,},
    ResultSearchParent : {position:"absolute",right:20,top:13},
    ResultSearchImg : {},

    searchCateBox :{paddingHorizontal:14,paddingVertical:10,flexDirection:"row",backgroundColor:"red",height:30},
    searchCateBoxCircle : {borderWidth:1,paddingHorizontal:8,borderColor:"#00B267",borderRadius:200,height:30,marginRight:5,justifyContent:"center"},
    searchCateBoxCircleActive :  { backgroundColor:"#00B267"},
    searchCateBoxCircleText : {color:"#00B267"},
    searchCateBoxCircleTextActive : {color:"#FFF",fontWeight:"600"},


    searchFilterBox :{paddingHorizontal:12,paddingBottom:5,flexDirection:"row",height:30,alignItems:"center"},
    searchFilterBoxCircle : {height:30,marginRight:8,justifyContent:"center"},
    searchFilterBoxCircleText : {color:"#808080",fontSize:12},
    searchFilterBoxCircleTextActive : {color:"#000",fontWeight:"600"},

    MainViewCartAbs : {position:"absolute", width:"100%",height:100,backgroundColor:"#000", bottom:60},

    main_banner_h100 : {width:"100%", height:100,backgroundColor:"#dfdfdf"},
    mainRollingBox : {paddingVertical:15,},
    MainGrayBar5 : {width:"100%", height:5, backgroundColor:"#F4F4F4"},
    MainGrayBar10 : {width:"100%", height:10, backgroundColor:"#F4F4F4"},
    mainAdBannerView : {paddingHorizontal:15,width:"100%"},
    mainAdBannerViewImg : {borderRadius:10,},

    EmpryLineBox:{borderBottomWidth:0, borderStyle:"solid", borderColor:"#dfdfdf", marginBottom:15, paddingBottom:15,},
    EmpryLineBox2:{borderBottomWidth:1, borderStyle:"solid", borderColor:"#dfdfdf", },
    MainViewTitleTxt: { fontSize: 16, color: "#0D0D0D", fontFamily: Fonts.Pretendard, letterSpacing: -.5, marginTop:10},
    MainViewTitlePrice : {marginTop:0,},
    MainViewTitlePriceText: {fontSize: 14, color: "#808080", fontFamily: Fonts.Pretendard, letterSpacing: -.5, },
    MainViewTitlePriceAdminText: {fontSize: 16, color: "#E41414", fontFamily: Fonts.Pretendard, letterSpacing: -.5, },
    MainViewTitleInfo: { fontSize: 13, color: "#808080", fontFamily: Fonts.Pretendard, letterSpacing: -.5, marginTop: 4 },
    MainViewTitle:{},
    MainViewDetail:{marginBottom:10, fontSize:14,fontFamily: Fonts.PretendardBold,},
    MainViewDetailTxt:{color:"#0d0d0d",},
    MainViewEtcImg : {marginTop:30},
    MoreItems:{marginTop:10,},
    MoreItemsList:{marginRight:15},
    MoreItemsBoxHoriSlide: {flexDirection : "row",flex:1},
    MoreItemsBox:{flexDirection:"row"},
    MainMinHeightBox : {minHeight:270},
    MoreItemImgbox:{position:"relative"},
    MoreItemImgboxOnly: {padding:5,paddingHorizontal:10, borderRadius:200, position:"absolute",right:5,bottom:5,zIndex:3,backgroundColor:"#C61C14"},
    MoreItemImgboxOnlyText: {color:"#fff",fontSize:12, fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    MoreItemImg:{width:150, height:150,borderRadius:4},
    MoreItemTxtBox:{paddingVertical:5},
    MoreItemTxtShop: {fontSize:12,  color: "#808080", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, lineHeight:18},
    MoreItemTxt01:{fontSize:12,  color: "#808080", fontFamily: Fonts.Pretendard, letterSpacing: -.5, lineHeight:16, width:150, },
    MoreItemTxt01Deco:{fontSize:12,  color: "#808080", fontFamily: Fonts.Pretendard, letterSpacing: -.5, lineHeight:16, textDecorationLine: 'line-through'},
    MoreDiscountShare: {flexDirection:"row",paddingVertical:3,alignItems:"center"},
    MoreDiscountSharePer : {fontSize:11,backgroundColor:"#AA0905",color:"#fff",marginRight:5,borderRadius:4,paddingVertical:2,paddingHorizontal:5},
    MoreItemTxtAdmin01:{fontSize:15,  color: "#E41414", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, lineHeight:16, width:150, },
    MoreItemTxt01High : {paddingTop:2, fontSize:14,  color: "#808080", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, lineHeight:18, width:120, },
    MoreItemTxt01black : {color:"#333"},
    MoreItemTxt02:{},
    BtPositionBox:{flexWrap:"wrap",flexDirection:"row", marginBottom:10,marginTop:10, bottom:0},
    BtPositionImgBox:{width:40,justifyContent:"center"},
    BtPositionLeft:{flex:2, flexDirection:"row"},
    BtPositionImg:{width:20, height:20, resizeMode:"contain"},
    BtPositionTxtBox:{justifyContent:"center"},
    BtPositionTxt:{color:"#000", fontSize:15,},
    BtPositionBtShare : {flexDirection:"row",justifyContent:"space-between",gap:10},
    BtPositionBtBox:{flex:3,  height:40, },
    BtPositionBt:{backgroundColor:"#cd2214", height:40,justifyContent:"center",alignItems:"center",borderRadius:4,flex:1},
    BtPositionBtGray:{backgroundColor:"#919191", height:40,justifyContent:"center",alignItems:"center",borderRadius:4},
    BtPositionBtText:{fontSize: 14, color: "#fff", fontFamily: Fonts.Pretendard,letterSpacing:-.5},
    BtPositionContain:{backgroundColor:"#fff"},
    MainViewYoutubeTextRed : {color:"#FF0000"},
   
    MainViewYoutubeView : {paddingTop:40,},
    MainViewYoutubeText : {fontSize: 14, color: "#000", fontFamily: Fonts.PretendardBold,letterSpacing:-.5,paddingBottom:10,},

    MainViewMiriBtn : {},
    MainViewMiriBtnText : {},

    /* AccountCreation */
    JoinArea:{},
    GreetingTXTArea:{paddingTop:30, paddingBottom:30},
    GreetingLine:{borderBottomWidth:1,marginTop:10, borderColor:"#e6e6e6",},
    GreetingTXT01:{color:"#0d0d0d", fontSize:20,lineHeight:30},
    GreetingTXT02:{color:"#808080", fontSize:12,lineHeight:25},
    JoinInsertArea:{width:80, height:80, backgroundColor:"#bbdef7", borderRadius:80, alignItems:"center", justifyContent: "center"},
    JoinInsertImg:{},
    AgreeArea:{marginBottom:100},
   
    /*RegionalSettingsScreen*/
    AreaTopMargin:{marginTop:30},
    NearbyArea:{marginTop:20},
    NearbyAreaTXT:{fontSize: 15, color:"#d0d0d0", lineHeight:40},

    /* LocationsScreen */
    AreaDivide:{},
    LocationHeadTxt:{ color: "#000", fontSize: 16, fontWeight: "600", marginTop: 10},
    NoStuff:{alignItems:"center", paddingTop:80, },
    NoStuffTxt:{},


    /*MainLogin*/
    LoseBoxText: { fontSize: 13, textAlign: "center", textDecorationLine: "underline" },




    //color: "#0d0d0d", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14, 

    /*모달 */
    um_background: { backgroundColor: "rgba(0,0,0,0,6)", flex: 1, justifyContent: "center", alignItems: "center", },
    um_whiteBox: { width: 300, backgroundColor: "white", borderRadius: 4, elevation: 2, },
    um_actionButton: { padding: 16, flexDirection: "row", alignItems: "center", },
    um_icon: { marginRight: 8, },
    um_text: { fontSize: 26, },
    pfmImgBoxImg: { height: 150, width: "100%", borderRadius: 4, },

    RegiModalBox: { zIndex: 3, left: 0, top: 0, position: "absolute", height: "100%", width: "100%", backgroundColor: "#000", opacity: .8 },
    RegiModalBoxItem: { zIndex: 3, left: 0, top: 0, position: "absolute", height: "100%", width: "100%", justifyContent: "center", alignContent: "center", alignItems: "center", },
    RegiModalBoxCont: { width: "90%", backgroundColor: "#fff", zIndex: 5, opacity: 1, borderRadius: 10, padding: 20 },
    RegiModalEditBoxCont: { width: "90%", backgroundColor: "#fff", zIndex: 5, opacity: 1, borderRadius: 4, padding: 4 },
    RegiModalEditBoxContBtn: {},
    RegiModalEditBoxContText: { paddingHorizontal: 20, fontSize: 12, lineHeight: 21, fontFamily: Fonts.Pretendard, letterSpacing: -.5, color: "#0D0D0D", paddingVertical: 8 },
    RegiModalEditBoxContTextDanger: { color: "#BB0F0F" },
    RegiModalTitle: { fontSize: 20, textAlign: "center", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, color: "#0D0D0D", paddingVertical: 24 },
    RegiModalContent: { fontSize: 14, textAlign: "center", lineHeight: 21, fontFamily: Fonts.Pretendard, letterSpacing: -.5, color: "#0D0D0D", opacity: .5 },
    RegiModalBtn: {  justifyContent: "center", height: 48, borderRadius: 5,borderWidth:1,borderColor:"#cd2214" },
    RegiModalBtnActive: { backgroundColor: "#cd2214", justifyContent: "center", height: 48, borderRadius: 5 },
    RegiModalBtnDanger: { backgroundColor: "#BB0F0F", justifyContent: "center", height: 48, borderRadius: 5 },
    RegiModalBtnText: { color: "#fff", textAlign: "center", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14 },
    RegiModalBtnTextBlue: { color: "#cd2214", textAlign: "center", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14 },
    RegiModalQ: { fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14, color: "#0D0D0D" },
    RegiModalA: { fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14, color: "#0D0D0D", opacity: .5, marginTop: 8, marginBottom: 16 },


    BuyModalBoxItem: { zIndex: 3, left: 0, top: 0, position: "absolute", height: "100%", width: "100%", justifyContent: "flex-end", alignContent: "center", alignItems: "center", },
    BuyModalBoxCont: { position:"absolute", bottom:0, width: "100%", backgroundColor: "#fff", zIndex: 5, opacity: 1, borderTopLeftRadius:24, borderTopRightRadius: 24, padding: 15 },
    BuyModalTitle: { fontSize: 17,  fontFamily: Fonts.PretendardBold, letterSpacing: -.5, color: "#0D0D0D", paddingTop: 10 },
    BuyButtonShare: {flexDirection:"row", justifyContent:"center"},
    BuyButtonShareStyle: {flex:1, height:40,borderWidth:1, borderColor:"#cd2214",borderRadius:4,justifyContent:"center",alignItems:"center"},
    BuyButtonShareTextStyle: {fontSize: 14,  fontFamily: Fonts.PretendardBold, letterSpacing: -.5, color: "#cd2214"},
    BuyButtonShareTextStyleW : {color:"#fff"},
    BuyButtonShareLeft: {marginRight:2},
    BuyButtonShareRight: {marginLeft:2, backgroundColor:"#cd2214"},
    BuyModalTitlePrice : {},
    BuyModalTitlePriceText: {fontSize: 17, color: "#E41414", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, },
    BuyModalDescView:{marginVertical:5,},
    BuyModalDescText:{fontSize: 13, color: "#555", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    BuyModalDescTextNick : {fontSize: 13, color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    BuyModalCountView : {flexDirection:"row", paddingVertical:10},
    BuyModalCountViewDelivery : {justifyContent:"center",flex:1},
    BuyModalCountTextInputView : {flexDirection:"row",justifyContent:"space-between",flex:1, alignItems:"center",borderWidth:1, borderColor:"#999", borderRadius:4,alignContent:"center",height:40},
    BuyModalCountTextInputLeft : {height:30,width:30,justifyContent:"center",alignItems:"center",},
    BuyModalCountTextInputCenter : {textAlignVertical:"center", paddingVertical:0,textAlign:"center", height:30,width:60,justifyContent:"center",alignItems:"center",lineHeight:30},
    BuyModalCountTextInputRight : {height:30,width:30,justifyContent:"center",alignItems:"center"},

    /*장바구니 */
    CartView :{paddingTop:10},
    CartShopTitle:{fontSize: 14, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,paddingBottom:10,paddingHorizontal:15},
    CartShopItemBox : {borderTopColor:"#F1F1F1",borderTopWidth:1,paddingVertical:15,},
    CartItemShare: {flexDirection:"row"},
    CartItemShareLeft: {width:55,paddingLeft:15},
    CartCheckBoxB : {width:25,height:25,borderWidth:0,borderColor:"#dfdfdf", borderRadius:4,},
    CartCheckBoxA : {width:30,height:30, borderRadius:4,backgroundColor:"#cd2214"},
    CartItemShareRight: {flex:1,paddingRight:15},
    CartItemShareShareRight : {width:70},
    CartItemShareShareLeft : {flex:1},
    CartItemShareRightImage : {width:60,height:60,},
    CartItemShareShare: {flexDirection:"row"},
    CartItemShareShareItemName : {fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartItemShareShareItemPrice : {fontSize: 14, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    CartItemShareShareDeliPrice : {fontSize: 13, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartCountTextInputView : {flexDirection:"row",justifyContent:"flex-end",flex:1, alignItems:"center",marginTop:10},
    CartCountTextInputViewShare: {flexDirection:"row",justifyContent:"flex-end",flex:1, alignItems:"center",borderWidth:1, borderColor:"#999",borderRadius:4},
    CartCountDeleteButton : {borderWidth:1, borderColor:"#999",height:30,paddingHorizontal:20, justifyContent:"center",alignItems:"center",borderRadius:4},
    CartCountDeleteButtonText: {fontSize: 13, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartCountTextInputLeft : {height:28,width:30,justifyContent:"center",alignItems:"center",},
    CartCountTextInputCenter : {height:28,width:60,textAlignVertical:"center", paddingVertical:0,textAlign:"center", justifyContent:"center",alignItems:"center",lineHeight:28},
    CartCountTextInputRight : {height:28,width:30,justifyContent:"center",alignItems:"center",},
    CartShopCalcView:{ backgroundColor:"#F1FAFF",paddingVertical:10,alignItems:"center",borderTopColor:"#E5E5E5",borderTopWidth:0,borderBottomColor:"#E5E5E5",borderBottomWidth:1},
    CartShopCalcText : {fontSize: 13, color: "#555", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartBottomOrderShare: {flexDirection:"row",},
    CartBottomOrderLeft : {flex:1,paddingHorizontal:15,paddingVertical:5,borderTopColor:"#f1f1f1",borderTopWidth:1},
    CartBottomOrderRight : {flex:1,justifyContent:"center",alignItems:"center",paddingHorizontal:15,paddingVertical:5,backgroundColor:"#cd2214",borderTopRightRadius:20},
    CartBottomOrderRightText: {fontSize: 15, color: "#fff", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    CartBottomOrderRightDisable : {flex:1,justifyContent:"center",alignItems:"center",paddingHorizontal:15,paddingVertical:5,backgroundColor:"#C8C8C8",borderTopRightRadius:20},
    CartBottomOrderLeftShare:{flexDirection:"row"},
    CartBottomOrderLeftShareLeft:{flex:1, fontSize: 12, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartBottomOrderLeftShareRight1:{flex:1,textAlign:"right",fontSize: 12, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    CartBottomOrderLeftShareRight2:{flex:1,textAlign:"right",fontSize: 13, color: "#E41414", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    
    

    /*주문페이지 */
    OrderBoxScroll: {backgroundColor:"#d9d9d9",},
    OrderBoxWrap: {padding:5},
    OrderBasicBox : {backgroundColor:"#fff",marginBottom:5},
    OrderBasicBoxHead : {flexDirection:"row",borderBottomColor:"#dfdfdf",borderBottomWidth:1, paddingHorizontal:15,paddingVertical:10},
    OrderBasicBoxHeadLeft: {flex:1,fontSize: 14, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderBasicBoxHeadRight: {width:50, justifyContent:"center",alignItems:"flex-end",},
    OrderBasicBoxHeadRightArrow: {width:15,height:15},


    OrderBasicBoxBodyType1: {backgroundColor:"#fff", flexDirection:"row",paddingHorizontal:15,paddingVertical:10,borderBottomColor:"#dfdfdf",borderBottomWidth:1,},
    OrderBasicBoxBodyType1Left : {flex:1},
    OrderBasicBoxBodyType1Right : {width:80,alignItems:"flex-end"},
    OrderNewAdrrBtn : {padding:10},
    OrderNewAdrrBtnPress: {backgroundColor:"#cd2214",height:40,flex:1,borderRadius:4},
    OrderNewAdrrBtnPressText: {fontSize: 15, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5, justifyContent:"center",flex:1,textAlignVertical:"center",textAlign:"center",lineHeight:40},
    orderBtn1: {paddingVertical:7, paddingHorizontal:12,backgroundColor:"#A1A7AE",width:60,alignItems:"center",borderRadius:4},
    orderBtn1Text: {fontSize: 13, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderBasicOdName : {fontSize: 15, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderBasicOdTel : {fontSize: 13, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderBasicOdAddress : {fontSize: 14, lineHeight:20, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},

    OrderBasicBoxBodyMemo: {padding:10,backgroundColor:"#F8F9FB"},
    OrderBasicBoxBodyMemoShare: {backgroundColor:"#fff",borderWidth:1,borderColor:"#DFE0E2"},
    OrderBasicBoxBodyMemoShareSelect : {height:30,},
    OrderBasicBoxBodyMemoSelecter : {padding:15},


    inputIOS: {
        fontSize: 16,
        height: 50, 
        width: 300, 
        color: '#000000',
        borderColor: '#000000', 
        borderWidth: 1, 
        borderRadius: 12,
        padding: 10
    },
    inputAndroid: {
        fontSize: 16,
        height: 50, 
        width: 300, 
        color: '#000000',
        borderColor: '#000000', 
        borderWidth: 1, 
        borderRadius: 12,
        padding: 10
    },

    OrderProductListBox: {},
    OrderProductListShop: {},
    OrderProductListShopTitle: {flexDirection:"row",borderBottomWidth:0,borderBottomColor:"#dfdfdf",paddingHorizontal:15,paddingVertical:10},
    OrderProductListShopTitleLeft: {flex:1,fontSize: 14, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderProductListShopTitleRight: {width:40},
    OrderProductListShopItemBox: {paddingHorizontal:15,paddingVertical:5},
    OrderProductListShopItemCont: {paddingVertical:0,flexDirection:"row"},
    OrderProductListShopItemContLeft: {width:100,minHeight:60},
    OrderProductListShopItemContRight: {flex:1},
    OrderProductListShopItemContRightItName: {fontSize: 14, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderProductListShopItemContRightItQty: {fontSize: 14, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderProductListShopItemContRightItPrice: {fontSize: 14, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderProductListShopPriceBox: {backgroundColor:"#F1FAFF",padding:15,paddingVertical:15,marginTop:5,},
    OrderProductListShopPriceBoxLeft: {width:100,fontSize: 15, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderProductListShopPriceBoxRight: {flex:1,textAlign:"left",fontSize: 13, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,marginTop:5},

    OrderProductListShopPriceBox2: {flexDirection:"row", justifyContent:"space-between", backgroundColor:"#F1FAFF",padding:15,paddingVertical:15,marginTop:5,},
    OrderProductListShopPriceBoxLeft2: {width:100,fontSize: 15, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderProductListShopPriceBoxRight2: {flex:1,textAlign:"right",fontSize: 16, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},


    OrderPaySelectBox: {padding:10,paddingVertical:15},
    OrderPaySelectItem: {flexDirection:"row",height:30,justifyContent:"center"},
    OrderPaySelectItemLeft: {width:30,justifyContent:"center"},
    OrderPaySelectItemLeftRadio: {width:20,height:20,borderWidth:1,borderColor:"#dfdfdf",borderRadius:200,position:"relative"},
    OrderPaySelectItemRightText: {flex:1, fontSize: 15, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,height:30,textAlignVertical:"center",lineHeight:30},
    OrderPaySelectItemLeftRadioActive: {width:10,height:10,top:4,left:4, borderRadius:200,position:"absolute", backgroundColor:"#cd2214"},

    OrderEndBox:{paddingVertical:10,paddingHorizontal:15},
    OrderEndShare:{flexDirection:"row",paddingVertical:2},
    OrderEndShareLeft:{flex:1},
    OrderEndShareRight:{width:100,textAlign:"right"},
    OrderEndFont1:{fontSize: 14, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderEndFont2:{fontSize: 13, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderEndPriceShare:{},
    OrderEndPriceLeft:{},
    OrderEndPriceRight:{},
    OrderLastPayBtnBox: {flex:1,paddingVertical:15,justifyContent:"center",backgroundColor:"#cd2214",borderRadius:4},
    OrderLastPayTextBox: {textAlign:"center",fontSize: 15, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderUsePointView : {flexDirection:"row",justifyContent:"space-between",alignItems:"center"},
    OrderUsePointView2 : {flexDirection:"row",justifyContent:"flex-end",alignItems:"center",marginTop:5},
    OrderUsePointViewText: {},
    OrderUsePointViewTextInput: {borderWidth:1, borderColor:"#dfdfdf",borderRadius:4,width:"100%",textAlign:"center",height:40},
    OrderUsePointViewButton: {backgroundColor:"#fff",justifyContent:"center",borderRadius:4,marginLeft:5,borderWidth:1, borderColor:"#dfdfdf",height:40},
    OrderUsePointViewButtonBlue: {borderColor:"#cd2214"},
    OrderUsePointViewButtonRed: {borderColor:"#ED1C24"},
    OrderUsePointViewButtonDisable : {borderColor:"#d1d1d1"},
    OrderUsePointViewButtonText: {color:"#333",paddingHorizontal:10,textAlign:"center",paddingVertical:5,fontSize: 13, fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderUsePointViewButtonTextBlue : {color:"#cd2214"},
    OrderUsePointViewButtonTextRed : {color:"#ED1C24"},
    OrderUsePointViewButtonTextDisable: {color:"#999",height:40,paddingHorizontal:10,lineHeight:40},
    OrderUsePointViewCouponText: {color:"#333",height:40,lineHeight:40},
    OrderUsePointViewCouponTextDisable: {color:"#999",height:40,lineHeight:40},
    OrderUseCouponViewButton: {},
    OrderUseCouponLayer: {paddingVertical:10},
    OrderUseCouponLayerItem: {flexDirection:"row",justifyContent:"space-between",paddingVertical:10,alignItems:"center",borderColor:"#dfdfdf", borderWidth:1,borderRadius:4,paddingHorizontal:10,marginVertical:3,minHeight:60},
    OrderUseCouponLayerItemDesc: {flex:1, paddingRight:10,},
    OrderUseCouponLayerItemDescDisable: {color:"#999"},
    OrderUseCouponLayerItemDescBig: {color:"#111",fontSize: 15,  fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderUseCouponLayerItemDescSmall: {fontSize: 12,  fontFamily: Fonts.Pretendard, letterSpacing: -.5,color:"#ED1C24",marginTop:4,},
    OrderUseCouponLayerItemBtn: {width:80,backgroundColor:"#0060A3",justifyContent:"center",borderRadius:4},
    OrderUseCouponLayerItemBtnRed: {width:80,backgroundColor:"#ED1C24",justifyContent:"center",borderRadius:4},
    OrderUseCouponLayerItemBtnDisable: {backgroundColor:"#fff",borderWidth:1, borderColor:"#d1d1d1"},
    OrderUseCouponLayerItemText: {color:"#fff",textAlign:"center",paddingVertical:5,fontSize: 13, fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderUseCouponLayerItemTextDisable: {color:"#999"},


    AddressScroll : {flex:1, padding:15},
    AddressViewBox : {},
    AddressItemBox: {padding:15,borderWidth:1, borderColor:"#f1f1f1"},
    AddressItemText1: {fontSize: 15, color: "#000", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    AddressItemText2: {fontSize: 15, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,paddingVertical:3,},
    AddressItemText3: {fontSize: 15, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    AddressItemShare: {flexDirection:"row",paddingVertical:5,},
    AddressItemShareBox: {fontSize: 13, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,borderWidth:1, borderColor:"#d1d1d1",paddingVertical:2,paddingHorizontal:10,borderRadius:200},
    AddressItemBtnShare: {flexDirection:"row",marginTop:10,},
    AddressItemBtnShareBtn : {flex:1,borderWidth:1, borderColor:"#dfdfdf",borderRadius:4},
    AddressItemBtnShareBtn2 : {borderWidth:1, borderColor:"#cd2214",borderLeftWidth:0,backgroundColor:"#cd2214",},
    AddressItemBtnShareBtnText: {textAlign:"center",flex:1,height:30,textAlignVertical:"center",lineHeight:30},
    AddressItemBtnShareBtnText2 : {color:"#fff"},
    OrderNewAdrrBtnArea : {height:60},
    OrderItemShareRightImage : {width:90,height:90,borderRadius:4},

    AddressNewContBox: {flex:1,padding:15},
    AddressNewContBoxText: {fontSize: 15, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    AddressNewContBoxTextInput: {fontSize: 15, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5, borderWidth:1,borderColor:"#dfdfdf",height:35,marginTop:5,marginBottom:10,borderRadius:4,paddingHorizontal:5,paddingVertical:0},
    AddressNewContBoxTextInputShare: {flexDirection:"row"},
    AddressNewContBoxTextInputShareLeft: {flex:1},
    AddressNewContBoxTextInputShareRight: {width:50,paddingLeft:3,justifyContent:"center",borderRadius:4},
    AddressNewContBoxTextInputShareRightText: {marginTop:1, height:35, textAlign:"center",textAlignVertical:"center",backgroundColor:"#cd2214", color:"#fff",borderRadius:4,lineHeight:35},
    AddressNewContSaveBasicAddr : {flexDirection:"row"},
    AddressNewContSaveBasicAddrChk : {width:25,height:25,borderWidth:1,borderRadius:4,borderColor:"#dfdfdf"},
    AddressNewContSaveBasicAddrText : {flex:1, paddingLeft:10,fontSize: 15, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    AddressNewContSaveBasicAddrChkActive : {borderColor:"#cd2214", backgroundColor:"#cd2214"},


    OrderResultView : {backgroundColor:"#ddd",padding:0,flex:1},
    OrderResultViewTop : {backgroundColor:"#fff",paddingHorizontal:10,paddingVertical:30},
    OrderResultViewTopText : {textAlign:"center",fontSize: 21, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderResultViewTopTextBlue: {color:"#cd2214", fontSize: 21,},
    OrderResultViewMid : {paddingVertical:15,paddingHorizontal:15,backgroundColor:"#fff",borderTopColor:"#dfdfdf", borderTopWidth:1,},
    OrderResultViewMidShare : {flexDirection:"row",paddingVertical:8,},
    OrderResultViewMidShareLeft : {width:100,fontSize: 14, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderResultViewMidShareRight : {flex:1,fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderResultViewMidShareRightText1 : {fontSize: 14, color: "#000", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderResultViewMidShareRightText2 : {fontSize: 18, color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderResultBtn : {height:40,borderRadius:4,backgroundColor:"#cd2214", justifyContent:"center",marginTop:20,paddingHorizontal:15},
    OrderResultBtnText :{textAlign:"center",fontSize: 15, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},

    ReviewsTopShare: {flexDirection:"row",padding:15},
    ReviewsTopShareLeft: {flexDirection:"row",flex:1,alignItems:"center"},
    ReviewsTopShareRight: {flex:1,alignItems:"flex-end"},
    ReviewsScoreText : {fontSize:21},
    ReviewsSortShare: {padding:15,borderTopWidth:1,borderTopColor:"#dfdfdf", borderBottomWidth:1,borderBottomColor:"#dfdfdf",flexDirection:"row"},
    ReviewsSortShareLeft: {flex:1},
    ReviewsSortShareRight: {flex:1, alignItems:"flex-end", justifyContent:"flex-end", flexDirection:"row",textAlign:"left"},
    ReviewsSortShareRightText : {paddingLeft:15,textAlign:"right"},
    ReviewsSortShareRightTextActive: {color:"#cd2214", fontFamily: Fonts.PretendardBold,},
    Reviewsview_avg_star_share_img : {width:25,height:25,},
    Reviewsview_avg_star_share_img_small : {width:15,height:20,},

    ReviewsStoryViewContent : {padding:15},
    ReviewsStoryViewShare : {flexDirection:"row",},
    ReviewsStoryViewShareLeft : {width:60},
    ReviewsStoryViewShareLeftImage : {width:50,height:50,borderRadius:200},
    ReviewsStoryViewShareRight : {flex:1},
    ReviewsStoryViewShareRightName : {fontSize: 16, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    ReviewsStoryViewShareRightStarShare : {flexDirection:"row",paddingVertical:4},
    ReviewsStoryViewShareRightStarShareLeft : {flexDirection:"row"},
    ReviewsStoryViewShareRightStarShareRight : {},
    ReviewsStoryViewShareRightStarShareRightText : {paddingVertical:1,paddingLeft:10, fontSize: 13, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    ReviewsStoryViewShareRightSellerName : {fontSize: 16, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    ReviewsStoryViewOptionText : {paddingVertical:5,fontSize: 13, color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    ReviewsStoryViewDetailText: {fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,paddingBottom:10,},

    OrderHistoryBox : {padding:15,},
    OrderHistoryBoxTopShare : {flexDirection:"row",justifyContent:"space-between"},
    OrderHistoryBoxTopShareLeft : {fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxTopShareRight : {fontSize: 16, color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxMid : {borderWidth:1, borderColor:"#dfdfdf",borderRadius:4,padding:15,marginTop:10,},
    OrderHistoryBoxMidDeliveryShare : {flexDirection:"row",justifyContent:"space-between"},
    OrderHistoryBoxMidDeliveryShareLeft : {flexDirection:"row"},
    OrderHistoryBoxMidDeliveryShareLeftText1 : {fontSize: 14, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderHistoryBoxMidDeliveryShareLeftText2 : {fontSize: 17, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,paddingLeft:5},
    OrderHistoryBoxMidDeliveryShareRight : {},
    OrderHistoryBoxMidDeliveryShareRightText : {fontSize: 13, color: "#cd2214", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderHistoryBoxMidItemShare : {flexDirection:"row", justifyContent:"space-between", paddingVertical:10,},
    OrderHistoryBoxMidItemShareLeft : {width:80,height:80,},
    OrderHistoryBoxMidItemShareLeftImg : {width:80,height:80,borderRadius:4},
    OrderHistoryBoxMidItemShareRight : {flex:1,paddingLeft:10},
    OrderHistoryBoxMidItemShareRightText1 : {fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxMidItemShareRightText2View : {},
    OrderHistoryBoxMidItemShareRightText : {fontSize: 14, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxMidBtnShare : {flexDirection:"row", justifyContent:"space-between"},
    OrderHistoryBoxMidBtnShareLeft : {flex:1},
    OrderHistoryBoxMidBtnShareLeftText : {paddingVertical:6,borderRadius:4, borderWidth:1, borderColor:"#dfdfdf",textAlign:"center",fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxMidBtnShareRight : {flex:1},
    OrderHistoryBoxMidBtnShareRightRight : {paddingVertical:6,borderRadius:4,borderWidth:1, borderColor:"#cd2214",textAlign:"center",fontSize: 14, color: "#cd2214", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    OrderHistoryBoxMidTextInput : {textAlignVertical: "top", borderWidth:1,borderColor:"#dfdfdf",paddingVertical:10,paddingHorizontal:10,height:100,marginTop:5,},
    OrderHistoryBoxPress: {backgroundColor:"#cd2214",justifyContent:"center",borderRadius:4,marginTop:5},
    OrderHistoryBoxPressText: {color:"#fff",textAlign:"center",height:40,width:"100%",lineHeight:40},
    OrderHistoryBoxBottomBtn : {flex:1,},
    OrderHistoryBoxBottomBtnText : {paddingVertical:6,fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,textAlign:"center",backgroundColor:"#F5F5F5", borderWidth:1,borderColor:"#F5F5F5",borderRadius:4},
    OrderHistoryBoxBottomRvBtnText : {paddingVertical:6,fontSize: 14, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,textAlign:"center",backgroundColor:"#cd2214",borderRadius:4},
    OrderHistoryBoxBottomRvBtnTextCont: {paddingBottom:10},
    OrderHistoryBoxBottomBtnMuBankView: {paddingVertical:10,justifyContent:"center",borderRadius:4,marginTop:10,borderWidth:1, borderColor:"#cd2214"},
    OrderHistoryBoxBottomBtnMuBankViewIntro: {textAlign:"center",fontSize: 15, paddingBottom:3, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderHistoryBoxBottomBtnMuBankViewContent: {textAlign:"center",fontSize: 14, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},

    OrderHistoryBoxBottomInfoView : {padding:10,backgroundColor:"#F5F5F5",borderRadius:4,marginTop:10},
    OrderHistoryBoxBottomInfoViewText : {fontSize: 14,lineHeight:18, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,textAlign:"center",marginTop:10},
    OrderHistoryBoxBottomInfoViewShare: {flexDirection:"row",justifyContent:"space-between",paddingVertical:3},
    OrderHistoryBoxBottomInfoViewShareLeft: {width:100,fontSize: 13, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OrderHistoryBoxBottomInfoViewShareRight: {flex:1,fontSize: 13, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,textAlign:"right"},

    OrderHistoryBoxSaChakBox: {marginTop:5,},
    OrderHistoryBoxSaChakBoxText: {fontSize: 14,lineHeight:18, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    

    Register2View: {padding:15, paddingVertical:30},
    Register2ViewIntro: {textAlign:"center", fontSize: 16,lineHeight:25, color: "#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    Register2ViewComponent: {paddingVertical:40,},
    Register2ViewHpInput: {borderWidth:1, borderColor:"#dfdfdf",height:50,textAlign:"center",borderRadius:4},
    Register2ViewBtn: {marginVertical:10,alignItems:"center",justifyContent:"center",borderRadius:4,backgroundColor:"#dfdfdf",alignContent:"center",},
    Register2ViewBtnActive : {backgroundColor:"#cd2214",},
    Register2ViewBtnText: {fontSize: 14, color: "#999", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,height:50,width:"100%",textAlign:"center",lineHeight:48},
    Register2ViewBtnTextActive :{color:"#fff"},
    Register2ViewCertInput: {borderWidth:1, borderColor:"#dfdfdf",height:50,textAlign:"center",borderRadius:4},

    OCSView : {paddingHorizontal:15, paddingVertical:10},
    OCSTitle : {fontSize: 17, color: "#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    OCSReasonView : {paddingVertical:10,marginTop:10,},
    OCSReasonViewRadio : {flexDirection:"row",paddingVertical:10,},
    OCSReasonViewRadioText : {fontSize: 14, color: "#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5,paddingLeft:10,},
    OCSReasonViewTextarea : {},
    OCSReasonViewTextareaInput : {borderWidth:1,borderColor:"#dfdfdf",padding:10,textAlignVertical: "top",height:70},
    OCSBtnPress : {justifyContent:"center",alignItems:"center",paddingHorizontal:15,paddingVertical:10,backgroundColor:"#cd2214",marginTop:10,borderRadius:4},
    OCSBtnPressText: {fontSize: 15, color: "#fff", fontFamily: Fonts.PretendardBold, letterSpacing: -.5},

    BBSView: {paddingVertical:10,paddingHorizontal:15,},
    BBSViewDesc: {fontSize: 15, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5},
    BBSViewList : {flexDirection:"row",justifyContent:"space-between",flexWrap:"wrap",marginTop:20,paddingHorizontal:10},
    BBSViewListBox : {flex:1,alignItems:"center",minWidth:95,minHeight:130,justifyContent:"center"},
    BBSViewListBoxImg : {width:70,height:70,},
    BBSViewListBoxImgCover : {position:"relative", width:80,height:80,backgroundColor:"#F2F2F2",borderRadius:15,alignItems:"center",justifyContent:"center"},
    BBSViewListBoxImgCoverNewIcon : {position:"absolute",width:8,height:8,borderRadius:200,backgroundColor:"#FF7A6B",top:8,right:8,zIndex:10000},
    BBSViewListBoxText: {fontSize: 14, color: "#555", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,paddingTop:3},

    CCSView : {paddingVertical:20,paddingHorizontal:15,fontSize: 14, color: "#555", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},


    MQSView: {flex:1,padding:15},
    MQSViewItemInfoShare: {flexDirection:"row", justifyContent:"space-between"},
    MQSViewItemInfoShareImg: {width:80},
    MQSViewItemInfoShareText: {flex:1},
    MQSViewItemInfoShareTextOdId: {fontSize: 14, color: "#cd2214", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    MQSViewItemInfoShareTextShopName: {fontSize: 14, color: "#777", fontFamily: Fonts.PretendardBold, letterSpacing: -.5,},
    MQSViewItemInfoShareTextItName: {fontSize: 18, color: "#333", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    MQSViewConfirmBtn : {paddingVertical:15,justifyContent:"center",backgroundColor:"#cd2214",borderRadius:4},
    MQSViewConfirmBtnText : {textAlign:"center",fontSize: 15, color: "#fff", fontFamily: Fonts.Pretendard, letterSpacing: -.5,},
    MQSViewTextarea: {height:150,fontSize:16,borderWidth:1,padding:15,borderColor:"#ddd",marginVertical:10,borderRadius:4,},

    USView : {justifyContent:"center",alignItems:"center"},
    USViewMainText : {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 17, color: "#0d0d0d" },
    USViewMainTextBef : {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#777" ,marginTop:20},
    USViewMainTextAft : {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#555" },
    USViewMainBtn : {backgroundColor:"#cd2214",paddingVertical:10,paddingHorizontal:20,borderRadius:200,marginTop:20},
    USViewMainBtnText : {color:"#fff",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 15, },

    DESTopView: {paddingHorizontal:15,},
    DESTopViewInner: {paddingVertical:20},
    DESTopViewInnerBoxIntro: {paddingVertical:20,},
    DESTopViewInnerIntro: {textAlign:"center",color:"#cd2214",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 17, },
    DESTopViewInnerIntroDesc : {textAlign:"center",color:"#777",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14, },
    DESTopViewInnerInfo: {flexDirection:"row",paddingVertical:3,},
    DESTopViewInnerInfoH: {width:100,fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14,},
    DESTopViewInnerInfoD: {flex:1,fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14,},
    DESTopViewBottom: {},
    DESTopViewBottomTbl: {},
    DESTopViewBottomTblTh: {padding:15,borderBottomWidth:1, borderBottomColor:"#dfdfdf",flexDirection:"row",justifyContent:"space-between"},
    DESTopViewBottomTblThText: {flex:1,textAlign:"center"},
    DESTopViewBottomTblTd: {padding:15,borderBottomWidth:1, borderBottomColor:"#EFEFEF",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},
    DESTopViewBottomTblTdText: {flex:1,textAlign:"center"},
    DESTopViewBottomTblNoData: {paddingVertical:30,alignItems:"center"},
    DESTopViewBottomTblNoDataText: {textAlign:"center",width:"100%",color:"#999", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16,},

    popBadgeView: {flexDirection:"column",justifyContent:"center"},
    popBadgeViewIn : {alignItems:"center",alignContent:"center"},
    popBadgeViewInImg: {width:80,height:80,},
    popBadgeViewInText : {color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14,},

    MPCSView: {},
    MPCSViewTopShare: {padding:15,flexDirection:"row",justifyContent:"space-between"},
    MPCSViewTopShareLeft: {width:90,justifyContent:"center"},
    MPCSViewTopShareLeftImg: {width:70,height:70,borderRadius:200},
    MPCSViewTopShareRight: {flex:1},
    MPCSViewTopShareRightName: {color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 21,},
    MPCSViewTopShareRightInfoShare2 : {flexDirection:"row",alignItems:"center",paddingBottom:10},
    MPCSViewTopShareRightInfoShare2Right:{flexDirection:"row",alignItems:"center"},
    MPCSViewTopShareRightInfoShare: {flexDirection:"row",justifyContent:"space-between",alignItems:"center"},
    MPCSViewTopShareRightInfoShareLeft: {width:100,color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14,},
    MPCSViewTopShareRightInfoShareRight: {flex:1,color:"#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 14,},
    MPCSViewBot: {},
    MPCSViewBotTitle: {padding:15,color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14,},
    MPCSViewBotShare: {padding:15,flexDirection:"row",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#dfdfdf"},
    MPCSViewBotShareLeft: {flex:1,paddingRight:10,},
    MPCSViewBotShareLeftTitle: {color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 17,},
    MPCSViewBotShareLeftDesc: {color:"#777", fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13,},
    MPCSViewBotShareRight: {width:100,justifyContent:"center",alignItems:"center",borderWidth:1,borderColor:"#FF7A6B",borderRadius:10,paddingVertical:10,},
    MPCSViewBotShareRightText1: {color:"#333", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 12,},
    MPCSViewBotShareRightText2: {color:"#FF7A6B", fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 17,},

    MQLSView: {},
    MQLSViewItem: {borderBottomWidth:1,borderBottomColor:"#dfdfdf",borderTopWidth:1,borderTopColor:"#dfdfdf",},
    MQLSViewItemQShare: {padding:15,flexDirection:"row",justifyContent:"space-between"},
    MQLSViewItemQShareLeft: {flex:1,},
    MQLSViewItemQShareLeftText1: {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16, color: "#0d0d0d",paddingRight:10, },
    MQLSViewItemQShareLeftText2: {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#777" ,marginTop:5,},
    MQLSViewItemQShareRight: {},
    MQLSViewItemQShareRightText1: {borderWidth:1,paddingHorizontal:10,paddingVertical:7,borderRadius:4,textAlign:"center",borderColor:"#777",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#777"},
    MQLSViewItemQShareRightText1Green : {color:"#22B14C",borderColor:"#22B14C"},
    MQLSViewItemA: {padding:15,backgroundColor:"#FAFAFA"},
    MQLSViewItemAView: {},
    MQLSViewItemAViewTextShop: {fontFamily: Fonts.PretendardBold, letterSpacing: -.5, fontSize: 14, color: "#cd2214"},
    MQLSViewItemAViewText1: {fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16, color: "#0d0d0d" },
    MQLSViewItemAViewText2: {marginTop:5, fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#777" },

    CLCateView : {borderBottomWidth:1,borderBottomColor:"#dfdfdf",padding:15},
    CLCBoxMaster: {padding:15},
    CLCBoxShare: {flexDirection:"row",justifyContent:"space-between",display:"flex",flex:1},
    CLCBoxLeft: {flex:1},
    CLCBoxLeftSubject: {},
    CLCBoxLeftSubjectCate: {},
    CLCBoxLeftSubjectCont: {fontSize:14,lineHeight:18},
    CLCBoxLeftEtc: {flexDirection:"row",gap:10,marginTop:5},
    CLCBoxLeftEtcNick: {fontSize:12,marginRight:5},
    CLCBoxLeftEtcTime: {fontSize:12,marginRight:5},
    CLCBoxLeftEtcHit: {fontSize:12,marginRight:5},
    CLCBoxMid: {width:50,marginLeft:10},
    CLCBoxMidImage: {width:50,height:50,borderRadius:7},
    CLCBoxRight: {width:50,height:50,marginLeft:10,justifyContent:"center",alignContent:"center",alignItems:"center"},
    CLCBoxRightCommentNum: {fontWeight:"600",fontSize:15},
    CLCBoxRightCommentText: {fontSize:12},

    RegiModalBoxOpacity: { zIndex: 3, left: 0, top: 0, position: "absolute", height: "100%", width: "100%", backgroundColor: "#000", opacity: .0 },
    optionModalView: {
        
        position: "absolute", right: 24, top: 0, backgroundColor: "#fff", paddingHorizontal: 15, borderRadius: 4, minWidth: 120,
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: {
                    width: 10,
                    height: 10,
                },
                shadowOpacity: 0.5,
                shadowRadius: 10,
            },
            android: {
                elevation: 20,
            },
        }),
    },
    optionModalViewText: { fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 13, color: "#0d0d0d" },
    optionModalViewTextDel: { color: "red" },
    optionModalViewPress: { paddingVertical: 8 },
    
    
    EMSView : {padding:15,justifyContent:"center",alignItems:"center",flex:1},
    EMSViewTitle : { fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16, color: "#777",textAlign:"center",lineHeight:22},
    EMSViewTextInput : {height:40, borderWidth:1,borderColor:"#dfdfdf",width:"100%",textAlign:"center",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 20, color: "#ED1C24",lineHeight:22,marginVertical:20,borderRadius:4},
    EMSViewBtn : {backgroundColor:"#ED1C24",height:50,borderRadius:4,justifyContent:"center",alignItems:"center",width:"100%"},
    EMSViewBtnText : {color:"#fff",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16,textAlign:"center",},

    MPSView : {flex:1,padding:15,justifyContent:"center",alignItems:"center"},
    MPSViewTitle: {textAlign:"center",color:"#333",lineHeight:23, fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16,},
    MPSViewInput: {height:50,borderWidth:1,borderColor:"#dfdfdf",borderRadius:4,width:"100%",textAlign:"center",marginVertical:20,color:"#777",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 20,},
    MPSViewBtn: {height:50,borderRadius:4,backgroundColor:"#ED1C24",width:"100%",alignContent:"center",alignItems:"center",justifyContent:"center"},
    MPSViewBtnText: {color:"#fff",fontFamily: Fonts.Pretendard, letterSpacing: -.5, fontSize: 16,},

    /*모달 끝 */


    /*Update */
    UPSView :{flex:1,justifyContent:"center",alignContent:"center",alignItems:"center"},
    UPSViewTitle :{fontSize:21,fontWeight:"600",marginBottom:10},
    UPSViewVer :{color:"#777",fontSize:12},
    UPSViewButton :{marginTop:10,backgroundColor:"#F95949",textAlign:"center",justifyContent:"center",paddingVertical:10,paddingHorizontal:30,borderRadius:4},
    UPSViewTButtonText :{color:"#fff"},


});

export default styles;